### ISSUE TITLE
ionic serve error

### ISSUE THREAD

**Issue by ghost** [Temeteron/ionic2-firebase-starter-kit#1] opened 2017-05-19 01:19 UTC
I have followed all of the instructions.

When I use ionic serve it gets all the way to 'dev server running: http...(etc)'
then it says

[ERROR] app-scripts serve unexpectedly failed.settings: undefinedcontext: [object Object]
any ideas?

**Comment by Temeteron** [comment] 2017-05-19 06:41
Check if your package.json is the same with the one of the repo. Can you provide any code or a printscreen from your terminal?

Something possibly is different in your app modules or the package.json.

I also updated the readme file. You possibly haven't installed Node.js in your system.

I also found [this](https://forum.ionicframework.com/t/app-scripts-serve-unexpectedly-failed-settings-undefinedcontext-object-object/90578/6), which indicates that ionic has a problem.

Please try again and let me know!

**Comment by Temeteron** [comment] 2017-05-19 15:26
I found the solution for this error. The problem is the latest ionic cli v3.2.1. This one crashes on ionic serve. The bug is at the ionic cli and not at this tutorial, as stated on the [ionic official blog](https://forum.ionicframework.com/t/app-scripts-serve-unexpectedly-failed-settings-undefinedcontext-object-object/90578/6)

# Solution
You can run (ionic serve) this tutorial succesfuly by running:
```bash
sudo npm install -g ionic@2.1.18
```
which will install the ionic cli v2.1.18, that doesn't crash on "ionic serve".

You can obviously return to the latest ionic cli version, after the completion of this project by:
```bash
sudo npm install -g ionic
```
Let me know about your progress  and if this solution works for you, so that i can close the issue!

**Comment by Temeteron** [comment] 2017-05-19 19:38
Closing for now. Feel free to reopen!

**Closed as completed by Temeteron** 2017-05-19 19:38 UTC
